name: Build & Test
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: az-paas-ecs-runners
    steps:
      - name: Get value
        id: vault
        uses: az-soft-eng/Vault-Action@v1.1.0
        env:
          VAULT_TOKEN: ${{ secrets.vault_token }}
          VAULT_URL: ${{ secrets.vault_url }}
        with:
          path: ${{ secrets.vault_path }}
          key: FakeUser
      - name: Verify data
        run: echo "${{ steps.vault.outputs.value }}" | grep FakePassword